baseURL: "https://miaoyunfa-lab.github.io/"
languageCode: "zh-cn"
title: "苗运法研究员课题组"
summaryLength: 30
params:
  lab_name: "苗运法研究员课题组"
  show_header_navigation: false
  tagline: "欢迎访问我们的学术主页"
  pi_name: "苗运法"
  affiliation: "中国科学院西北生态环境资源研究院"
  email: "miaoyunfa@lzb.ac.cn"
  address: "甘肃省兰州市城关区东岗西路320号，730000，中国"
  hero_text: "孢粉学与生态环境研究组"
  research_groups:
    - title: "研究方向"
      items:
        - title: "孢粉学基础"
          text: "旨在改进孢粉提取流程，拓展新型指标，探索智能化识别技术，研发孢粉学专用仪器"
        - title: "生态环境演变"
          text: "旨在重建多时空尺度下生态气候、地形演变及生物多样性，探讨与自然和人类活动的关系"
        - title: "生态环境健康"
          text: "旨在分析表土、水体、大气多载体花粉动态变化过程，预测区域生态演化趋势，构建致敏花粉综合治理方案"
menu:
  main:
    - name: "首页"
      url: "/"
      weight: 1
    - name: "新闻"
      url: "/news/"
      weight: 2
    - name: "研究"
      url: "/research/"
      weight: 3
    - name: "成员"
      url: "/people/"
      weight: 4
    - name: "联系"
      url: "/contact/"
      weight: 6
markup:
  goldmark:
    renderer:
      unsafe: true
