baseURL: "https://miaoyunfa-lab.github.io/"
languageCode: "zh-cn"
title: "苗运法研究员课题组"
summaryLength: 30
params:
  lab_name: "苗运法研究员课题组"
  show_header_navigation: false
  tagline: "欢迎访问我们的学术主页"
  pi_name: "苗运法"
  affiliation: "中国科学院西北生态环境资源研究院"
  email: "miaoyunfa@lzb.ac.cn"
  address: "甘肃省兰州市城关区东岗西路320号，730000，中国"
  hero_text: "孢粉学与生态环境研究组"
  hero_subtext: "以孢粉为核心，解码过去生态环境与气候演变，服务未来"
  research_groups:
    - title: "研究方向"
      items:
        - title: "孢粉学"
          text: "聚焦孢粉学基础与关键技术，开展孢粉室内提取与自动化鉴定研究，拓展代用指标体系（微炭屑），推动孢粉学相关仪器的研发与应用；"
        - title: "古生态与干旱环境演化"
          text: "探讨过去生态环境变化，包括全球气候变化、地形演变、生物多样性及碳循环过程，系统重建亚洲内陆区域生态与气候演变历史；"
        - title: "全球变化生态学"
          text: "研究空气花粉、植被现代过程及致敏花粉的动态变化，分析其对气候变化与人类活动的响应机制，预估未来生态演变趋势与应对策略。"
menu:
  main:
    - name: "首页"
      url: "/"
      weight: 1
    - name: "新闻"
      url: "/news/"
      weight: 2
    - name: "研究"
      url: "/research/"
      weight: 3
    - name: "成员"
      url: "/people/"
      weight: 4
    - name: "联系"
      url: "/contact/"
      weight: 6
markup:
  goldmark:
    renderer:
      unsafe: true
